# -*- coding: utf-8 -*-
"""
Created on Wed May 26 19:11:43 2021

@author: Yue
"""

urlstr = 'JTY4JTc0JTc0JTcwJTczJTNBJTJGJTJGJTc2JTY5JTY0JTY1JTZGJTJFJTYyJTc1JTc5JTYzJTYxJTcyJTM1JTJFJTYzJTZFJTJGJTMyJTMwJTMyJTMwJTMxJTMwJTMwJTM5JTJGJTdBJTMyJTUyJTQ1JTZCJTQ3JTQxJTM2JTJGJTY5JTZFJTY0JTY1JTc4JTJFJTZEJTMzJTc1JTM4'
def GetPass(urlstr):
    urlstr = urlstr.replace('JTY0', 'd')
    urlstr = urlstr.replace('JTQx', 'A')
    urlstr = urlstr.replace('JTQ2', 'F')
    urlstr = urlstr.replace('JTcx', 'q')
    urlstr = urlstr.replace('JTQ1', 'E')
    urlstr = urlstr.replace('JTY4', 'h')
    urlstr = urlstr.replace('JTM5', '9')
    urlstr = urlstr.replace('JTM2', '6')
    urlstr = urlstr.replace('JTZC', 'k')
    urlstr = urlstr.replace('JTM1', '5')
    urlstr = urlstr.replace('JTRF', 'N')
    urlstr = urlstr.replace('JTUy', 'R')
    urlstr = urlstr.replace('JTQ3', 'G')
    urlstr = urlstr.replace('JTUx', 'Q')
    urlstr = urlstr.replace('JTRD', 'L')
    urlstr = urlstr.replace('JTc4', 'x')
    urlstr = urlstr.replace('JTcz', 's')
    urlstr = urlstr.replace('JTJF', '.')
    urlstr = urlstr.replace('JTc0', 't')
    urlstr = urlstr.replace('JTYz', 'c')
    urlstr = urlstr.replace('JTZE', 'm')
    urlstr = urlstr.replace('JTQy', 'B')
    urlstr = urlstr.replace('JTU2', 'V')
    urlstr = urlstr.replace('JTMw', '0')
    urlstr = urlstr.replace('JTMy', '2')
    urlstr = urlstr.replace('JTRB', 'J')
    urlstr = urlstr.replace('JTU4', 'X')
    urlstr = urlstr.replace('JTM3', '7')
    urlstr = urlstr.replace('JTQz', 'C')
    urlstr = urlstr.replace('JTY5', 'i')
    urlstr = urlstr.replace('JTdB', 'z')
    urlstr = urlstr.replace('JTU3', 'W')
    urlstr = urlstr.replace('JTUz', 'S')
    urlstr = urlstr.replace('JTc1', 'u')
    urlstr = urlstr.replace('JTY2', 'f')
    urlstr = urlstr.replace('JTRE', 'M')
    urlstr = urlstr.replace('JTc5', 'y')
    urlstr = urlstr.replace('JTZB', 'j')
    urlstr = urlstr.replace('JTQ0', 'D')
    urlstr = urlstr.replace('JTRG', 'O')
    urlstr = urlstr.replace('JTVB', 'Z')
    urlstr = urlstr.replace('JTU5', 'Y')
    urlstr = urlstr.replace('JTQ4', 'H')
    urlstr = urlstr.replace('JTU1', 'U')
    urlstr = urlstr.replace('JTZG', 'o')
    urlstr = urlstr.replace('JTcy', 'r')
    urlstr = urlstr.replace('JTY3', 'g')
    urlstr = urlstr.replace('JTMx', '1')
    urlstr = urlstr.replace('JTYx', 'a')
    urlstr = urlstr.replace('JTcw', 'p')
    urlstr = urlstr.replace('JTZD', 'l')
    urlstr = urlstr.replace('JTM0', '4')
    urlstr = urlstr.replace('JTZF', 'n')
    urlstr = urlstr.replace('JTM4', '8')
    urlstr = urlstr.replace('JTJG', '/')
    urlstr = urlstr.replace('JTNB', ':')
    urlstr = urlstr.replace('JTU0', 'T')
    urlstr = urlstr.replace('JTc3', 'w')
    urlstr = urlstr.replace('JTUw', 'P')
    urlstr = urlstr.replace('JTYy', 'b')
    urlstr = urlstr.replace('JTc2', 'v')
    urlstr = urlstr.replace('JTY1', 'e')
    urlstr = urlstr.replace('JTRC', 'K')
    urlstr = urlstr.replace('JTMz', '3')
    urlstr = urlstr.replace('JTQ5', 'I')
    return urlstr
